webproject/webapp/urls.py
from django.urls import path
from . import views
app_name='webapp'

urlpatterns=[
    path('',views.index,name='index'),
    path('registration/',views.registration,name='registration'),
    path('login/',views.login,name='login'),
    path('home/<int:id>',views.home,name='home'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('changepassword/<int:id>',views.changepassword,name='changepassword'),
    path('logout/',views.logout,name='logout'),
    path('gallery/',views.gallery,name='gallery'),
    path('details/<int:id>',views.details,name='details'),
]

webproject/webproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webapp.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

webproject/webapp/models.py
from django.db import models

# Create your models here.
class Register(models.Model):
    Name=models.CharField(max_length=10)
    Age=models.IntegerField()
    Place=models.CharField(max_length=10)
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)
    Email=models.EmailField()
    Password=models.CharField(max_length=10)

class Gallery(models.Model): 
   Brand=models.CharField(max_length=10)
   Name=models.CharField(max_length=10)
   Photo=models.ImageField(upload_to='media/',null=True,blank=True)
   Price=models.IntegerField()
# Create your models here.

webproject/webapp/forms.py
from django import forms
from . models import Register
class RegisterForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    class Meta():
        model=Register                                         
        fields='__all__'

class LoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    class Meta():
        model=Register
        fields=('Email','Password')

class UpdateForm(forms.ModelForm):
    class Meta():
        model=Register
        fields=('Name','Age','Place','Email')
        
class ChangepasswordForm(forms.Form):
    OldPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    NewPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)

webproject/webapp/views.py
from django.shortcuts import render,redirect
from django.contrib import messages

from webproject import settings
from.forms import RegisterForm, LoginForm, UpdateForm,ChangepasswordForm
from .models import Register,Gallery
from django.contrib.auth import logout as logouts
from django.core.mail import send_mail

# Create your views here.
def index(request):
    return render(request,'index.html')
def registration(request):
    if request.method=='POST':
        form=RegisterForm(request.POST,request.FILES)
        if form.is_valid():
            name=form.cleaned_data['Name']
            age=form.cleaned_data['Age']
            photo=request.FILES['Photo']
            place=form.cleaned_data['Place']
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            confirmpassword=form.cleaned_data['ConfirmPassword']

            user=Register.objects.filter(Email=email).exists()
            if user:
                messages.warning(request,'Email Alredy exist')
                return redirect('/login')
            elif password!=confirmpassword:
                messages.warning(request,'Password Mismatch')
            else:
                tab=Register(Name=name,Age=age,Place=place,Email=email,Photo=photo,Password=password)
                tab.save()
                subject='welcome to mysite'
                message=f'Hi{name},thank you for registering in ddddd'
                email_form=settings.EMAIL_HOST_USER
                receipient_list=[email,]
                send_mail(subject,message,email_form,receipient_list)
                messages.success(request,'DATA SAVED')
                return redirect('/')
    else:
        form=RegisterForm() 
    return render(request,'registration.html',{'form':form})
    
def login(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            try:
                user=Register.objects.get(Email=email)
                if not user:
                    messages.warning(request,'Email does not exist')
                    return redirect('/login')
                elif password!=user.Password:
                    messages.warning(request,'Password Incorrect')
                    return redirect('/login')
                else:
                    messages.success(request,'Success')
                    return redirect('/home/%s' % user.id)
            except:
                messages.warning(request,'Email or Password incorrect')
                return redirect('/login')
    else:
        form=LoginForm()
    return render(request,'login.html',{'form':form})
def home(request,id):
        user=Register.objects.get(id=id)
        return render(request,'home.html',{'user':user})

def update(request,id):
    user=Register.objects.get(id=id)
    if request.method=='POST':
        form=UpdateForm(request.POST or None,instance=user)
        if form.is_valid():
            form.save()
            messages.success(request,'Success')
            return redirect('/home/%s' % user.id)
    else:
        form=UpdateForm(instance=user)
    return render(request,'update.html',{'user':user,'form':form})

def delete(request):
    user=Register.objects.get(id=id)
    user.delete()
    messages.success(request,'SUCCESS')
    return redirect('/')

def logout(request):
    logouts(request)
    messages.success(request,'SUCCESS')
    return redirect('/')

def changepassword(request,id):
    user=Register.objects.get(id=id)
    if request.method=='POST':
        form=ChangepasswordForm(request.POST or None)
        if form.is_valid():
            oldpassword=form.cleaned_data['OldPassword']
            newpassword=form.cleaned_data['NewPassword']
            confirmpassword=form.cleaned_data['ConfirmPassword']

            if oldpassword!= user.Password:
                messages.warning(request,"incorrect")
                return redirect('/changepassword/%s' % user.id)
            elif oldpassword==newpassword: 
                messages.warning(request, "password similar")
                return redirect('/changepassword/%s' % user.id)
            elif newpassword!=confirmpassword:
                messages.warning(request,"password new")
                return redirect('/changepassword/%s'% user.id)
            else:
                user.Password=newpassword
                user.save()
                messages.success(request,"change success")
    else:
        form=ChangepasswordForm()
        return render(request,'changepassword.html',{'user':user, 'form':form})

def logout(request):
    logouts(request)
    messages.success(request,"logged out")
    return redirect('/')

def gallery(request):
    images=Gallery.objects.all()
    return render(request,'gallery.html',{'images':images})

def details(request, id): 
    images=Gallery.objects.get(id=id)
    return render(request,'details.html',{'images':images}) 

webproject/webapp/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>
                {{form.as_table}}
            </tr>
        </table>
        <input type="submit" value="changepassword">
    </form>
</body>
</html>

webproject/webapp/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{images.id}}
    {{images.Brand}}
    {{images.Name}}
    {{images.Price}}
    
    <img style="width:200px;height:100px;" src="{{4_dutch_windmill.gif__700x700_q85_subsampling-2.jpg}}">
    
    </body>
</html>

webproject/webapp/templates/gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   

  <table>
    <tr>
        <th>Name</th>
        <th>Photo</th>
        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    </tr>
    {% for img in images %}
    <tr>
        <td>{{img.Name}}</td>
        <td><a href="{% url 'webapp:details' img.id %}"><img src="{{4_dutch_windmill.gif__700x700_q85_subsampling-2.jpg }}" height="100px" width="200px"></a></td>
        
    </tr>
    {% endfor %}</td>
    </tr>
</table>

webproject/webapp/templates/home.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    {{user.id}}
    {{user.Name}}
    {{user.Age}}
    {{user.Photo}}
    {{user.Email}}
    {{user.Place}}
    <img src="{{user.Photo.url}}" height="100px" width="200px">

    <a href="{% url 'webapp:update' user.id %}">Update</a>
    <a href="{% url 'webapp:delete' user.id %}">Delete</a>
    <a href="{% url 'webapp:logout' %}">logout</a>

   
</body>
</html>

webproject/webapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
    <a href="{% url 'webapp:login' %}">Login</a>
    <a href="{% url 'webapp:gallery' %}">Gallery</a>
    
    </form>
    
</body>
</html>

webproject/webapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post" >
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}} </tr>
        </table>            
        <input type="submit" value="Login">
    </form>
    <a href="{% url 'webapp:registration' %}">Create account</a>
</body>
</html>

webproject/webapp/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}}</tr>
        </table>
        <input type="submit" value="submit">
       
    </form>
      
</body>
</html>

webproject/webapp/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}}</tr>
        </table>
        <input type="submit" value="update">
       
    </form>
      
</body>
</html>